services:
  _defaults:
    autowire: true
    autoconfigure: true

  Francoisvaillant\TwigTrace\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

  Francoisvaillant\TwigTrace\Twig\Loader\DebugLoaderDecorator:
    decorates: 'twig.loader.native_filesystem'
    arguments:
      $loader: '@.inner'
      $debug: '%kernel.debug%'
      $separatorMacroStart: '%separator_macro_start%'
      $separatorMacroEnd: '%separator_macro_end%'
      $separatorBlockStart: '%separator_block_start%'
      $separatorBlockEnd: '%separator_block_end%'
      $excludedBlocks: '%excluded_blocks%'
      $excludedMacros: '%excluded_macros%'
      $excludedPaths: '%excluded_paths%'

  Francoisvaillant\TwigTrace\Twig\Extension\HtmlCommentExtension:
    tags: [ 'twig.extension' ]
    arguments:
      $separatorTemplateStart: '%separator_template_start%'
      $separatorTemplateEnd: '%separator_template_end%'
